#' Compare responses
#'
#' \code{ar_compare} compares responses across participant variables.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param participant_vars a \code{character} vector specifying the grouping variables.
#' @param target_var an optional \code{character} string specifying the target variable to be summarized. If not specified \code{ar_comapre} tabulates the frequencies of targets.
#' @param normalize an optional \code{character} string specifying whether the output should be normalized by rows (\code{normalize = "rows"}) or columns (\code{normalize = "columns"}). Defaults to \code{normalize = NULL} implying no normalization.
#'
#' @return Returns an \code{tibble} conatining grouped summaries (means or frequencies).
#'
#'
#' @examples
#'
#' ai_asso <- ai_asso %>%
#'   ar_define_targets(source = "cues")
#'
#' @export

ar_compare = function(associations,
                      participant_vars,
                      target_var = "targets",
                      fun = c("mean","count"),
                      normalize = NULL){

  # checks
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_subset("targets", names(associations))
  chk::chk_subset(participant_vars, names(associations$participants))

  # get groups
  data = associations$responses %>%
    left_join(associations$participants %>% select(id, dplyr::all_of(participant_vars)), by = "id") %>%
    left_join(associations$targets, by = c("response" = "target"))

  # set target
  if(target_var == "targets"){
    data = data %>% dplyr::mutate(value = 1)
    } else {
    chk::chk_subset(target_var, names(associations$targets))
    data = data %>% dplyr::mutate(value = .[[target_var]])
    }


  # resolve fun
  if(is.character(fun)){
    if(fun[1] == "count") fun = sum
    if(fun[1] == "mean") fun = mean
    }

  # count targets
  out = data %>%
    dplyr::filter(response %in% associations$targets$target) %>%
    dplyr::group_by(dplyr::across(dplyr::all_of(c(participant_vars, "response")))) %>%
    dplyr::summarize(value = fun(value)) %>%
    ungroup() %>%
    tidyr::pivot_wider(names_from = response, values_from = value)


  %>%
    mutate_at(-1, replace_na, 0)


}
