#' Compare responses
#'
#' \code{ar_compare} compares responses across participant variables.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param participant_vars a \code{character} vector specifying the grouping variables.
#' @param target_var an optional \code{character} string specifying the target variable to be summarized. If not specified \code{ar_comapre} tabulates the frequencies of targets.
#' @param fun a \code{character} string or a function specifying the statistic to calculate from \code{target_var}.
#'
#' @return Returns an \code{tibble} containing grouped summaries (means, frequencies, or other custom statistics).
#'
#'
#' @examples
#'
#' ai_asso %>%
#'   ar_ar_compare()
#'
#' @export

ar_compare = function(associations,
                      participant_vars,
                      target_var,
                      fun = c("count","mean")){

  # checks
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_subset("targets", names(associations))

  # get vars
  p_vars = dplyr::enquo(participant_vars)
  t_var = dplyr::enquo(target_var)

  # get groups
  data = associations$responses %>%
    left_join(associations$participants %>% select(id, !!p_vars), by = "id") %>%
    right_join(associations$targets, by = c("response" = "target")) %>%
    mutate(target = response)

  if(!is.function(fun)){
    if(fun[1] == "count"){

      # do counts
      out = data %>%
        dplyr::group_by(across(c(!!p_vars, !!t_var))) %>%
        dplyr::summarize(n = length(!!t_var)) %>%
        ungroup() %>%
        tidyr::pivot_wider(names_from = !!t_var,
                           values_from = n) %>%
        mutate_all(replace_na, 0)

    }
    if(fun[1] == "mean"){

      # do mean
      out = data %>%
        dplyr::group_by(across(c(!!p_vars))) %>%
        dplyr::summarize(!!rlang::ensym(target_var) := mean(!!t_var, na.rm=T)) %>%
        ungroup()
    }
  } else {

    # do fun
    out = data %>%
      dplyr::group_by(across(c(!!p_vars))) %>%
      dplyr::summarize(!!rlang::ensym(target_var) := fun(!!t_var, na.rm=T)) %>%
      ungroup()

    }

  # out
  out

  }
