#' Join all associatoR tibbles into one
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#'
#' @return a \code{tibble} containing all joined data in associations.
#'
ar_export_all <- function(associations) {

  # type checks
  chk::chk_s3_class(associations, "associatoR")

  # content checks
  chk::chk_subset(names(associations), c("participants", "cues", "responses", "targets"))

  # join tibbles -----

  if (exists("targets")) {

    # prefix targets
    associations$targets <- associations$targets %>%
      dplyr::rename_with(.fn = \(x) paste0("target_", x),
                         .cols = !tidyselect::matches("target"))

    # targets are defined
    export <- associations$responses %>%
      dplyr::left_join(associations$participants, by = "id") %>%
      dplyr::left_join(associations$cues, by = "cue") %>%
      dplyr::left_join(associations$targets, by = c("response" = "target"),
                       keep = TRUE)

  } else {
    # participants, cues, responses are defined (but not targets)
    export <- associations$responses %>%
      dplyr::left_join(associations$participants, by = "id") %>%
      dplyr::left_join(associations$cues, by = "cue")
  }

  export

}

#' Write a csv file
#'
#' \code{ar_write_csv()} joins all data in an \code{associatoR} object into one table and writes the table to disk using readr::write_csv().
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param file a \code{character} to write to.
#' @param ... optional arguments passed to readr::write_csv()
#'
#' @return \code{ar_write_csv()} returns the joined associations as a tibble invisibly.
#' @export
#'
#' @examples
#'
#' ai_asso_imported %>%
#'   ar_set_target("responses") %>%
#'   ar_write_csv(file = "associations.csv")
#'
ar_write_csv <- function(associations, file, ...) {

  # type checks
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_string(file)

  # content checks
  chk::chk_subset(names(associations), c("participants", "cues", "responses", "targets"))

  # join the contents of associations into one tibble
  export <- ar_export_all(associations)

  # export using
  readr::write_csv(export, file, ...)

}
