#' Normalize responses in an associatoR object
#'
#' \code{ar_normalize} offers an interface to add self-defined normalization steps for responses in associatoR objects.
#'
#' @param x an \code{associatoR} object generated by associatoR::ar_import()
#' @param fun a \code{function} to apply to all responses (resp_text) in an associatoR object.
#' @param ... additional arguments passed on to \code{fun}.
#'
#' @return Returns an \code{associatoR} object containing a list of \code{tibble}s with \code{fun} applied to all responses:
#' \describe{
#'  \item{participants}{A tibble of all participants including \code{part_id}, and potentially additional participant-specific attributes \code{part_*}.}
#'  \item{cues}{A tibble of all cues including \code{cue_id}, \code{cue_text} and potentially additional cue-specific attributes \code{cue_*}.}
#'  \item{responses}{A tibble of all responses including \code{resp_id}, \code{resp_text} and potentially additional response-specific attributes \code{resp_*}.}
#' }
#'
#' @export
#'
#' @references Aeschbach, S., Mata, R., Wulff, D. U. (in progress). associatoR. psyArXiv
#'
#' @examples
#'
#'
#'
ar_normalize <- function(x, fun, ...) {

  # check if x is an object of class associatoR
  if(!(class(x) == "associatoR")) {
    stop("x must be an object of class associatoR, can be generated with associatoR::ar_import()")
  }

  # check if fun is a function
  if(!class(fun) == "function") {
    stop("fun must be a function")
  }

  args <- list(...)

  if(length(args) == 0) {
    x$responses$resp_text <- sapply(x$responses$resp_text,
                                    FUN = fun,
                                    USE.NAMES = FALSE)
  } else {
    x$responses$resp_text <- sapply(x$responses$resp_text,
                                    FUN = fun,
                                    ... = args,
                                    USE.NAMES = FALSE)
  }


  x


}
