#' Plot associations
#'
#' Generate a plot of an \code{associatoR} object.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import} with targets defined by \link[associatoR]{ar_set_targets}.
#' @param facet_by a \code{character} vector of variable names to generate facets.
#' @param top_n a \code{numeric} scalar
#' @param ... optional \code{logical} comparisons to filter the responses before computing frequencies.
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles:
#' \describe{
#'  \item{participants}{A tibble of participants including a participant \code{id} and potential participant attributes.}
#'  \item{cues}{A tibble of cues including a \code{cue} variable and potential cue attributes.}
#'  \item{responses}{A tibble of responses including a participant id, the cues, the responses, the response level, and additional response attributes.}
#' }
#'
#' @examples
#' ar_import(intelligence,
#'           participant = participant_id,
#'           cue = cue,
#'           response = response,
#'           participant_vars = c(gender, education),
#'           response_vars = c(response_position, response_level)) %>%
#'   ar_set_targets("cues") %>%
#'   plot(facets = "gender", top_n = 10)
#'
#' ar_import(intelligence,
#'           participant = participant_id,
#'           cue = cue,
#'           response = response,
#'           participant_vars = c(gender, education),
#'           response_vars = c(response_position, response_level)) %>%
#'   ar_set_targets("cues") %>%
#'   plot(facets = "education", top_n = 10, gender == "female")
#'
#' @method plot associatoR
#' @export

plot.associatoR <- function(associations, facet_by = NULL, top_n = 5, ...) {

  # checks
  check_object(associations)
  chk::chk_superset(names(associations), c("participants", "cues", "responses", "targets"), x_name = "The associatoR object passed to plot.associatoR()")
  if(!chk::vld_null(facet_by)) {chk::chk_subset(facet_by, names(associations$participants))}
  chk::chk_whole_number(top_n)
  chk::chk_gt(top_n, 0)

  # extract names
  target_names = names(associations$targets)
  names(associations$targets) = ifelse(target_names == "target", "target", paste0("target_", target_names))

  # join
  tbl = associations$participants %>%
    dplyr::left_join(associations$responses, by = "id") %>%
    dplyr::left_join(associations$cues, by = "cue") %>%
    dplyr::left_join(associations$targets %>% dplyr::mutate(is_target = TRUE), by = c("response" = "target")) %>%
    dplyr::filter(is_target)

  filters = dplyr::enquos(...)

  tbl = tbl %>%
    dplyr::filter(!!!filters) %>%
    dplyr::select(response, tidyselect::all_of(facet_by)) %>%
    dplyr::group_by_all() %>% # superseded, replace
    dplyr::summarize(n = dplyr::n()) %>%
    dplyr::ungroup()

  if(!is.null(facet_by)) {
    tbl = tbl %>%
      dplyr::group_by_at(-c(1, ncol(.))) %>%
      dplyr::arrange(dplyr::desc(n)) %>%
      dplyr::slice(1:min(top_n, dplyr::n())) %>%
      dplyr::ungroup()
  } else {
    tbl = tbl %>%
      dplyr::arrange(dplyr::desc(n)) %>%
      dplyr::slice(1:min(top_n, dplyr::n())) %>%
      dplyr::ungroup()
  }

  # plot
  tbl %>%
    ggplot2::ggplot(ggplot2::aes(x = n, y = response)) +
    ggplot2::geom_bar(stat = "identity") +
    ggplot2::facet_wrap(facet = facet_by, scales = "free") +
    ggplot2::theme_minimal() +
    ggplot2::labs(y = "Response", x = "Frequency")

  }

#' Plot word clouds
#'
#' Generate word cloud plots of response frequencies for \code{associatoR} object.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import} with targets defined by \link[associatoR]{ar_set_targets}.
#' @param facet_by names of variables to generate facets by.
#' @param color_by a \code{character} vector of variable names to generate facets.
#' @param top_n a \code{numeric} scalar
#' @param ... optional \code{logical} comparisons to filter the responses before computing frequencies.
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles:
#' \describe{
#'  \item{participants}{A tibble of participants including a participant \code{id} and potential participant attributes.}
#'  \item{cues}{A tibble of cues including a \code{cue} variable and potential cue attributes.}
#'  \item{responses}{A tibble of responses including a participant id, the cues, the responses, the response level, and additional response attributes.}
#' }
#'
#' @examples
#' ar_import(intelligence,
#'           participant = participant_id,
#'           cue = cue,
#'           response = response,
#'           participant_vars = c(gender, education),
#'           response_vars = c(response_position, response_level)) %>%
#'   ar_set_targets("cues") %>%
#'   plot(facets = "gender", top_n = 10)
#'
#' ar_import(intelligence,
#'           participant = participant_id,
#'           cue = cue,
#'           response = response,
#'           participant_vars = c(gender, education),
#'           response_vars = c(response_position, response_level)) %>%
#'   ar_set_targets("cues") %>%
#'   plot(facets = "education", top_n = 10, gender == "female")
#'
#' @export

ar_word_cloud <- function(associations, facet_col = cluster, facet_row = NULL, color_by = cluster, top_n = 30, ...) {

  # checks
  check_object(associations)
  check_targets(associations)

  # capture variables
  facet_row = dplyr::enquo(facet_row)
  facet_col = dplyr::enquo(facet_col)
  color_by = dplyr::enquo(color_by)

  # join
  tbl = associations$responses %>%
    dplyr::left_join(associations$targets, by = c("response" = "target")) %>%
    dplyr::left_join(associations$participants, by = "id") %>%
    dplyr::left_join(associations$cues, by = "cue")

  # count
  counts = tbl %>%
    dplyr::count(!!facet_row, !!facet_col, response) %>%
    dplyr::group_by(!!facet_row, !!facet_col) %>%
    dplyr::top_n(top_n) %>%
    dplyr::ungroup() %>%
    dplyr::left_join(associations$targets,
                     suffix = c("","_remove"),
                     by = c("response" = "target")) %>%
    dplyr::select(-dplyr::ends_with("_remove")) %>%
    suppressMessages()

  print(counts)

  # plot
  plot = counts %>%
    ggplot2::ggplot(mapping = aes(label = response, size = n, color = !!color_by)) +
      ggwordcloud::geom_text_wordcloud(...) +
      ggplot2::theme_void() +
      ggplot2::facet_grid(cols = vars(!!facet_col),
                          rows = vars(!!facet_row))

  plot

  }



