#' Plot associations
#'
#' Generate a plot of an \code{associatoR} object.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import} with targets defined by \link[associatoR]{ar_set_targets}.
#' @param facets a \code{character} vector of variable names to generate facets.
#' @param top_n a \code{numeric} scalar
#' @param ... optional \code{logical} comparisons to filter the responses before computing frequencies.
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles:
#' \describe{
#'  \item{participants}{A tibble of participants including a participant \code{id} and potential participant attributes.}
#'  \item{cues}{A tibble of cues including a \code{cue} variable and potential cue attributes.}
#'  \item{responses}{A tibble of responses including a participant id, the cues, the responses, the response level, and additional response attributes.}
#' }
#'
#' @examples
#' ar_import(intelligence,
#'           participant = participant_id,
#'           cue = cue,
#'           response = response,
#'           participant_vars = c(gender, education),
#'           response_vars = c(response_position, response_level)) %>%
#'   ar_set_targets("cues") %>%
#'   plot(facets = "gender", top_n = 10)
#'
#' ar_import(intelligence,
#'           participant = participant_id,
#'           cue = cue,
#'           response = response,
#'           participant_vars = c(gender, education),
#'           response_vars = c(response_position, response_level)) %>%
#'   ar_set_targets("cues") %>%
#'   plot(facets = "education", top_n = 10, gender == "female")
#'
#' @method plot associatoR
#' @export

plot.associatoR <- function(associations, facets = NULL, top_n = 5, ...) {

  # checks
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_superset(names(associations), c("participants", "cues", "responses", "targets"), x_name = "The associatoR object passed to plot.associatoR()")
  if(!chk::vld_null(facets)) {chk::chk_subset(facets, names(associations$participants))}
  chk::chk_whole_number(top_n)
  chk::chk_gt(top_n, 0)

  # extract names
  target_names = names(associations$targets)
  names(associations$targets) = ifelse(target_names == "target", "target", paste0("target_", target_names))

  # join
  tbl = associations$participants %>%
    dplyr::left_join(associations$responses, by = "id") %>%
    dplyr::left_join(associations$cues, by = "cue") %>%
    dplyr::left_join(associations$targets %>% dplyr::mutate(is_target = TRUE), by = c("response" = "target")) %>%
    dplyr::filter(is_target)

  filters = dplyr::enquos(...)

  tbl = tbl %>%
    dplyr::filter(!!!filters) %>%
    dplyr::select(response, tidyselect::all_of(facets)) %>%
    dplyr::group_by_all() %>% # superseded, replace
    dplyr::summarize(n = dplyr::n()) %>%
    dplyr::ungroup()

  if(!is.null(facets)) {
    tbl = tbl %>%
      dplyr::group_by_at(-c(1, ncol(.))) %>%
      dplyr::arrange(dplyr::desc(n)) %>%
      dplyr::slice(1:min(top_n, dplyr::n())) %>%
      dplyr::ungroup()
  } else {
    tbl = tbl %>%
      dplyr::arrange(dplyr::desc(n)) %>%
      dplyr::slice(1:min(top_n, dplyr::n())) %>%
      dplyr::ungroup()
  }

  # plot
  tbl %>%
    ggplot2::ggplot(ggplot2::aes(x = n, y = response)) +
    ggplot2::geom_bar(stat = "identity") +
    ggplot2::facet_wrap(facets = facets, scales = "free") +
    ggplot2::theme_minimal() +
    ggplot2::labs(y = "Response", x = "Frequency")

  }
