#' Subset associations
#'
#' Subset the \code{associatoR} object.
#'
#' Note that \code{ar_subset()} resets the \code{associatoR} object. Potential \code{targets} and \code{target_embedding} tibbles will be removed and have to be added again using \link[associatoR]{ar_set_targets}.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param ... optional \code{logical} comparisons filtering the participants, cues, or responses. Multiple filter arguments will be combined with an AND logic.
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles:
#' \describe{
#'  \item{participants}{A tibble of participants including a participant \code{id} and potential participant attributes.}
#'  \item{cues}{A tibble of cues including a \code{cue} variable and potential cue attributes.}
#'  \item{responses}{A tibble of responses including a participant id, the cues, the responses, the response level, and additional response attributes.}
#' }
#'
#' @examples
#'
#' ar_import(intelligence,
#'           participant = participant_id,
#'           cue = cue,
#'           response = response,
#'           participant_vars = c(gender, education),
#'           response_vars = c(response_position, response_level)) %>%
#'   ar_subset(gender == "female", education == "high school")
#'
#' @export

ar_subset <- function(associations, ...) {

  # delay eval
  filters = dplyr::enquos(...)

  # checks
  chk::chk_s3_class(associations, "associatoR")

  # extract names
  part_names = names(associations$participants)
  resp_names = names(associations$responses)
  cue_names = names(associations$cues)

  # join
  tbl = associations$participants %>%
    dplyr::left_join(associations$responses, by = "id") %>%
    dplyr::left_join(associations$cues, by = "cue")

  # filter
  tbl = tbl %>% dplyr::filter(!!!filters)

  # re-import
  associations = ar_import(tbl,
                           participant = id,
                           cue = cue,
                           response = response,
                           participant_vars = part_names[!part_names %in% "id"],
                           cue_vars = cue_names[!cue_names %in% "cue"],
                           response_vars = resp_names[!resp_names %in% c("id", "cue", "response")])


  # out
  associations
  }
