#' Subset associations
#'
#' Subset the \code{associatoR} object.
#'
#' Note that subsets resets the \code{associatoR} object. A potential \code{target} tibble will be removed and has to be added again using \link[associatoR]{ar_import}.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param ... optional \code{logical} comparisons filtering the responses before computing the frequencies.
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles:
#' \describe{
#'  \item{participants}{A tibble of participants including a participant \code{id} and potential participant attributes.}
#'  \item{cues}{A tibble of cues including a \code{cue} variable and potential cue attributes.}
#'  \item{responses}{A tibble of responses including a participant id, the cues, the responses, the response level, and additional response attributes.}
#' }
#'
#' @examples
#'
#' ai_asso <- ai_asso %>%
#'   ar_subset(id > 10, trial = 10)
#'
#' @export

ar_subset <- function(associations, ...) {

  # delay eval
  filters = dplyr::enquos(...)

  # checks
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_subset("targets", names(associations))

  # extract names
  part_names = names(associations$participants)
  resp_names = names(associations$responses)
  cue_names = names(associations$cues)

  # join
  tbl = associations$participants %>%
    dplyr::left_join(associations$responses, by = "id") %>%
    dplyr::left_join(associations$cues, by = "cue")

  # filter
  tbl = tbl %>% dplyr::filter(!!!filters)

  # re-import
  associations = ar_import(tbl,
                           participant = "id",
                           cue = "cue",
                           response = "response",
                           participant_vars = part_names[!part_names %in% "id"],
                           cue_vars = cue_names[!cue_names %in% "cue"],
                           response_vars = resp_names[!resp_names %in% c("id", "cue", "response", "level")])


  # out
  associations
  }
