#' Define target in an associatoR object
#'
#' \code{ar_define_target} defines the target level to further analyze in an associatoR object. This could be multiple cue words to analyze based on responses, response words to analyze based on an external embedding, or response words to analyze based on a second level of responses.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR](ar_import).
#' @param source a \code{character} of \code{c("cues", "responses")} specifying, which column in Participants contains targets.
#' @param response_level an optional positive \code{integer} specifying, which response-level contains targets (defaults to 1).
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles:
#' \describe{
#'  \item{participants}{A tibble of all participants including \code{p_id} to identify participants, and potentially additional participant attributes \code{p_attr_*}.}
#'  \item{cues}{A tibble of all cues \code{c_cue} and potentially additional cue attributes \code{c_attr_*}.}
#'  \item{responses}{A tibble of all participant's \code{p_id} cue \code{r_cue} and response \code{r_response} pairs including response levels \code{r_level}, as well as potentially additional responseattributes \code{r_attr_*}.}
#'  \item{targets}{A tibble of \code{target}s that will be analyzed by subsequent functions.}
#' }
#' @export
#'
#' @examples
#'
#' ai_asso_imported <- ai_asso_imported %>%
#'   ar_define_target(source = "responses")
#'
ar_define_target <- function(associations,
                             source = c("cues", "responses"),
                             response_level = 1) {

  # checks -----

  # check types
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_string(source)
  chk::chk_count(response_level)

  # check allowed values
  chk::chk_subset(source, c("cues", "responses"))

  # function body -----

  if (source == "cues") {
    targets <- associations$cues %>%
      dplyr::select(cue) %>%
      dplyr::distinct() %>%
      dplyr::rename(target = cue)
  }

  if (source == "responses") {
    targets <- associations$responses %>%
      dplyr::filter(level == response_level) %>%
      dplyr::select(response) %>%
      dplyr::distinct() %>%
      dplyr::rename(target = response)
  }

  associations$targets <- targets

  associations

}

#' Add a frequency variable to targets
#'
#' Adds a variable \code{frequency} to the Targets in an associatoR object .
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR](ar_import).
#' @param source a \code{character} of \code{c("cues", "responses")} specifying, which column in Participants contains targets.
#'
#' @return
#' @return Returns an \code{associatoR} object containing a list of tibbles:
#' \describe{
#'  \item{participants}{A tibble of all participants including \code{id} to identify participants, and potentially additional participant varables.}
#'  \item{cues}{A tibble of all cues \code{cue} and potentially additional cue variables.}
#'  \item{responses}{A tibble of all participant's \code{id} cue \code{r_cue} and response \code{response} pairs including response levels \code{level}, as well as potentially additional response variables}
#'  \item{targets}{A tibble of \code{target} and \code{frequency} that will be analyzed by subsequent functions.}
#' }
#' @export
#' @examples
#' ar_import(ai_asso, participant_id = "id",
#'                               response_col = "association_correct",
#'                               cue_type = "manual", cue_manual = "artificial intelligence",
#'                               participant_attributes = c("age", "gender", "use", "expertise"),
#'                               response_attributes = c("association", "trial")) %>%
#'   ar_normalize() %>%
#'   ar_define_target(source = "responses") %>%
#'   ar_target_add_frequency(source = "responses")
#'
ar_target_add_frequency <- function(associations,
                                    source = c("cues", "responses")) {

  # checks -----

  # check types
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_string(source)

  # check allowed values
  chk::chk_subset("targets", names(associations))
  chk::chk_subset(source, c("cues", "responses"))

  # function body -----

  if (source == "cues") {
    target_frequency <- associations$responses %>%
      dplyr::left_join(associations$targets,
                       by = c("cue" = "target"),
                       keep = TRUE) %>%
      dplyr::group_by(target) %>%
      dplyr::summarize(frequency = dplyr::n())
  }

  if (source == "responses") {
    target_frequency <- associations$responses %>%
      dplyr::left_join(associations$targets,
                       by = c("response" = "target"),
                       keep = TRUE) %>%
      dplyr::group_by(target) %>%
      dplyr::summarize(frequency = dplyr::n())
  }

  associations$targets <- associations$targets %>%
    dplyr::left_join(target_frequency)

  associations
}
