#' Set analysis targets
#'
#' \code{ar_set_target} defines the analysis targets (cues and/or responses).
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param target_sets a \code{character} string or vector specifying whether cues and/or responses should the targets of analysis. Must be one or both of \code{c("cues", "responses")}.
#' @param target_manual a \code{character} character specifying the analysis target. Overrides argument \code{target_sets}.
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles:
#' \describe{
#'  \item{participants}{A tibble of participants including a participant \code{id} and potential participant attributes.}
#'  \item{cues}{A tibble of cues including a \code{cue} variable and potential cue attributes.}
#'  \item{responses}{A tibble of responses including a participant id, the cues, the responses, the response level, and additional response attributes.}
#'  \item{targets}{A tibble of targets including the specified analysis target}
#' }
#'
#'
#' @examples
#'
#' ai_asso <- ai_asso %>%
#'   ar_define_targets(source = "cues")
#'
#' @export

ar_set_targets <- function(associations,
                          target_set = c("cues", "responses"),
                          target_manual = NULL) {

  # checks -----

  # check types
  chk::chk_s3_class(associations, "associatoR")

  # check allowed values
  if(is.null(target_manual)){

    # check if type correct
    chk::chk_character(target_set)
    chk::chk_subset(target_set, c("cues", "responses"))

    # container
    target_vec = c()

    # cues
    if("cues" %in% target_set){
      target_vec = c(target_vec, unique(associations$cues$cue))
    }

    # responses
    if("responses" %in% target_set){
      target_vec = c(target_vec, unique(associations$responses$response))
    }

    # set unique
    target_vec = unique(target_vec)

    } else {

    # check
    chk::chk_character(target_manual)

    # use manual
    target_vec = target_manual
    }

  # out -----

  targets = tibble::tibble(target = target_vec)
  associations$targets <- targets
  associations

  }

#' Count target occurences in responses
#'
#' Append the response \code{frequency} of each target to the \code{targets} table in the \code{associatoR} object.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param ... optional \code{logical} comparisons filtering the responses before computing the frequencies.
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles, with \code{targets} gaining a \code{frequency} column:
#' \describe{
#'  \item{participants}{A tibble of participants including a participant \code{id} and potential participant attributes.}
#'  \item{cues}{A tibble of cues including a \code{cue} variable and potential cue attributes.}
#'  \item{responses}{A tibble of responses including a participant id, the cues, the responses, the response level, and additional response attributes.}
#'  \item{targets}{A tibble of targets including the specified analysis target}
#' }
#'
#' @examples
#'
#' ar_import(ai_asso, participant = "id",
#'           response = "association_correct",
#'           cue_manual = "AI",
#'           participant_vars = c("age", "gender", "use", "expertise"),
#'           response_vars = c("association", "trial")) %>%
#'   ar_normalize() %>%
#'   ar_set_targets(target_set = "responses") %>%
#'   ar_count_targets()
#'
#' @export

ar_count_targets <- function(associations, ...) {

  # delay eval
  filters = dplyr::enquos(...)

  # checks
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_subset("targets", names(associations))

  # calc frequency
  frequencies = associations$responses %>%
    dplyr::filter(!!!filters) %>%
    dplyr::group_by(response) %>%
    dplyr::summarize(frequency = dplyr::n())

  # join
  associations$targets = associations$targets %>%
    dplyr::left_join(frequencies, by = c("target" = "response"))

  # handle NAs (in filtered counts)
  associations$targets$frequency[is.na(associations$targets$frequency)] <- 0

  # out
  associations
  }

#' Characterize targets using additional resources
#'
#' Append target characteristic to the \code{targets} table in the \code{associatoR} object. Specify characteristics and or manual look up table.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param characteristics a \code{character} string or vector specifying which word characteristics to add to \code{targets}. Must be one or multiple of \code{c("valence", "arousal", "dominance", "concreteness", "frequency")} or \code{NULL} to omit automatic addition of characteristics. Data on valence, arousal, and dominance are retrieved from Warriner et al. (2013), concreteness and frequency data are retrieved from Brysbaert et al. (2014).
#' @param manual a \code{data.frame} with two or more columns, one must be called "word" and is used to join all additional columns to respective targets, or \code{NULL} to omit manual addition of characteristics.
#'
#' @return Returns an \code{associatoR} object containing a list of tibbles, with \code{targets} gaining additional columns including the target characteristics:
#' \describe{
#'  \item{participants}{A tibble of participants including a participant \code{id} and potential participant attributes.}
#'  \item{cues}{A tibble of cues including a \code{cue} variable and potential cue attributes.}
#'  \item{responses}{A tibble of responses including a participant id, the cues, the responses, the response level, and additional response attributes.}
#'  \item{targets}{A tibble of targets including the specified analysis target, and word characteristics}
#' }
#'
#' @references
#' \itemize{
#'   \item{Warriner, A.B., Kuperman, V. & Brysbaert, M. Norms of valence, arousal, and dominance for 13,915 English lemmas. Behav Res 45, 1191–1207 (2013). https://doi.org/10.3758/s13428-012-0314-x}
#'   \item{Brysbaert, M., Warriner, A.B. & Kuperman, V. Concreteness ratings for 40 thousand generally known English word lemmas. Behav Res 46, 904–911 (2014). https://doi.org/10.3758/s13428-013-0403-5}
#' }
#'
#'
#'
#'
#' @examples
#' ar_import(fa_data,
#'           participant = "participantID", participant_vars = c("age", "gender"),
#'           cue = "cue", response = "response",
#'           response_vars = c("created_at", "pos")) %>%
#'   ar_normalize() %>%
#'   ar_set_targets("cues") %>%
#'   ar_characterize_targets()
#'
#' @export
ar_characterize_targets <- function(associations,
                                    characteristics = c("valence",
                                                       "arousal",
                                                       "dominance",
                                                       "concreteness",
                                                       "frequency"),
                                    manual = NULL) {

  # checks
  chk::chk_s3_class(associations, "associatoR")
  chk::chk_subset("targets", names(associations))
  chk::chk_null_or(characteristics, chk::chk_subset, c("valence",
                                                      "arousal",
                                                      "dominance",
                                                      "concreteness",
                                                      "frequency"))
  chk::chk_null_or(manual, chk::chk_data)
  if(!is.null(manual)) {
    chk::chk_subset("word", names(manual))
  }

  # retrieve valence, arousal, dominance ---
  # form Warriner, A.B., Kuperman, V. & Brysbaert, M. Norms of valence, arousal, and dominance for 13,915 English lemmas. Behav Res 45, 1191–1207 (2013). https://doi.org/10.3758/s13428-012-0314-x

  if(!is.null(characteristics) & ("valence" %in% characteristics | "arousal" %in% characteristics | "dominance" %in% characteristics)) {

    # download from publisher
    temp <- tempfile()
    download.file("https://static-content.springer.com/esm/art%3A10.3758%2Fs13428-012-0314-x/MediaObjects/13428_2012_314_MOESM1_ESM.zip", temp)
    warriner <- readr::read_csv(temp, show_col_types = FALSE) %>%
      suppressMessages()
    unlink(temp)

    warriner <- warriner %>%
      dplyr::select(word = Word,
                    valence = V.Mean.Sum,
                    arousal = A.Mean.Sum,
                    dominance = D.Mean.Sum) %>%
      dplyr::select(word, any_of(characteristics))

    # add selected characteristics to targets
    associations$targets <- associations$targets %>%
      dplyr::left_join(warriner, by = c("target" = "word"))
  }

  # retrieve concreteness, frequency ----
  # from Brysbaert, M., Warriner, A.B. & Kuperman, V. Concreteness ratings for 40 thousand generally known English word lemmas. Behav Res 46, 904–911 (2014). https://doi.org/10.3758/s13428-013-0403-5

  if(!is.null(characteristics) & ("concreteness" %in% characteristics | "frequency" %in% characteristics)) {

    # download from publisher
    temp <- tempfile()
    download.file("https://static-content.springer.com/esm/art%3A10.3758%2Fs13428-013-0403-5/MediaObjects/13428_2013_403_MOESM1_ESM.xlsx", temp)
    brysbaert <- readxl::read_excel(temp)
    unlink(temp)

    brysbaert <- brysbaert %>%
      dplyr::select(word = Word,
                    concreteness = Conc.M,
                    frequency = SUBTLEX) %>%
      dplyr::select(word, any_of(characteristics))

    # add characteristics to targets
    associations$targets <- associations$targets %>%
      dplyr::left_join(brysbaert, by = c("target" = "word"))

  }

  # if specified, add manual target characteristics

  if(!is.null(manual)) {

    # add characteristics to targets
    associations$targets <- associations$targets %>%
      dplyr::left_join(manual, by = c("target" = "word"))

  }

  # out
  associations

}

