#' Export wordlist
#'
#' \code{ar_wordlist_export()} exports a table of responses for manual spelling correction.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param folder a \code{character} string specifying where to write the table.
#' @param file a \code{character} string specifying the filename. Default is \code{"wordlist.csv"}.
#'
#' @return Writes a .CSV file to the hard drive.
#'
#' @references Aeschbach, S., Mata, R., Wulff, D. U. (in preparation)
#'
#' @examples
#'
#' ar_obj = ar_import(intelligence,
#'                    participant = participant_id,
#'                    cue = cue,
#'                    response = response,
#'                    participant_vars = c(gender, education),
#'                    response_vars = c(response_position, response_level)) %>%
#'   ar_normalize_manual(trimws, which = "left")
#'
#' ar_wordlist_export(ar_obj)
#'
#'@export

ar_wordlist_export = function(associations, folder, file = "wordlist_correction.csv"){

  # checks
  check_object(associations)
  chk::chk_dir(folder)
  chk::chk_character(file)

  # check if targets exist
  if("targets" %in% names(associations)) warning("Spell checking is should be performed prior to setting targets.")

  # add csv if necessary
  if(str_sub(stringr::str_to_lower(file), nchar(file)-3, nchar(file)) != ".csv") file = paste0(file, ".csv")

  # response tab
  tab = table(associations$responses$response)

  # construct tibble
  out = tibble(response = names(tab),
               response_correct = c(),
               response_frequency = c(tab))

  all = spelling::spell_check_text(out$response, lang = "de_DE")


  all = spelling::spell_check_text(acronyms$acronym %>% str_to_lower())

  ind = all$found %>% unlist() %>% unique()

  acronyms %>% slice(-ind) %>% print(n = 100)

}

