#' Export wordlist
#'
#' \code{ar_wordlist_export()} exports a table of responses for manual spelling correction.
#'
#' @param associations an \code{associatoR} object containing association data as generated by \link[associatoR]{ar_import}.
#' @param folder a \code{character} string specifying where to write the table.
#' @param file a \code{character} string specifying the filename. Default is \code{"wordlist.csv"}.
#'
#' @return Writes a .CSV file to the hard drive.
#'
#' @references Aeschbach, S., Mata, R., Wulff, D. U. (in preparation)
#'
#' @examples
#'
#' ar_obj = ar_import(intelligence,
#'                    participant = participant_id,
#'                    cue = cue,
#'                    response = response,
#'                    participant_vars = c(gender, education),
#'                    response_vars = c(response_position, response_level)) %>%
#'   ar_normalize_manual(trimws, which = "left")
#'
#' ar_wordlist_export(ar_obj)
#'
#'@export

ar_wordlist_export = function(associations, folder, file = "wordlist_correction.csv"){

  check_object(associations)


}

